# Generated by Django 4.2.4 on 2023-08-21 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='identifier',
        ),
    ]
